# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_postworktime_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postworktime',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
