# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 17:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0009_auto_20180802_1147'),
        ('stats', '0004_auto_20180808_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugWorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent_mins', models.IntegerField(default=0)),
                ('timestamp', models.DateField()),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugs.Post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='postworktime',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postworktime',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostWorkTime',
        ),
    ]
