# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orderlineitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='amount_donated',
            new_name='contribution',
        ),
    ]
