# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='amount_raised',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='contributors',
        ),
    ]
