# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20180717_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to=settings.AUTH_USER_MODEL),
        ),
    ]
