# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_auto_20180802_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_comment', to='features.Feature'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feature_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
