# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_auto_20180802_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.IntegerField(choices=[(1, 'Awaiting Pricing'), (2, 'Open'), (3, 'Working'), (4, 'Closed')], default=1, verbose_name='status'),
        ),
    ]
