# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 20:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_auto_20181001_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_feature_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
