# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 16:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0011_auto_20181001_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
    ]
