# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugs',
            options={},
        ),
        migrations.RemoveField(
            model_name='bugs',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='bugs',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
