# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_remove_post_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
