# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0006_auto_20180730_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
