# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0009_auto_20180802_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_post_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
